## Joseph Rochelle
## DSC 550 Data mining
## Week 4 Assignment (Text: Sentiment Analysis)

In [1]:
#Importing libraries
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
import nltk

#Setting Decimal point preference
np.set_printoptions(precision =2)

In [2]:
#Reading data frame
DailyDf= pd.read_csv('DailyComments.csv')  
DailyDf

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

**Manual Sentiment Analizer:**
    
The purpose of this section is to provide the reader with a means to count key words that are meaningful to the researcher. Based off the use cases, there may be a time where evaluating key words and phrases and providing meaning may be important. This section serves as a means to create a column for key words and counts then to summarize the data. 

In [3]:
corpus = DailyDf['comments']

In [4]:
#Vectorizing the words within the corpus, which is our text only comments.

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("")
print("vectorized words")
print("")
print(vectorizer.get_feature_names())
print("")
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())


#After turning the vectors into arrays we put it back into a data frame

df = pd.DataFrame({'text' : corpus})

#Check for positive words and negative words based off the schema established. I want to do linguistics connections like very bad super special later. 
#This methods counts the words in our text data frame, adding positive and negative columns. Then, calculated field column totallying.
df['positive1'] = df.text.str.count('good')
df['positive2']= df.text.str.count('special')
df['negative'] = df.text.str.count('bad')
df['TotScore'] = df.positive1 + df.positive2 - df.negative
df['TotCount'] = df.positive1 + df.positive2 + df.negative

print("")
print(df)

# Printing the results in a data frame based off the scoring of sentiment analysis above
Z = sum(df['TotScore'])
Z1= sum(df['TotCount'])
Z2 = Z/Z1


print("")
print("Overall Score:  ",Z)
print("Overall Count:  ",Z1)

# The % of sentiment that was negative. 
#While the researcher does not have to use negative sentiment as the numerator to the total count of words as the denominator, this researcher sought to bring that option to the analysis. 
print("Positive Sentiment %:"+" {:.2f}".format(Z2))



vectorized words

['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']

Identify Feature Words - Matrix View

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]

                                             text  positive1  positive2  \
0                             Hello, how are you?          0          0   
1                            Today is a good day!          1          0   
2  It's my birthday so it's a really special day!          0          1   
3       Today is neither a good day or a bad day!          1          0   
4                           I'm having a bad day

**With NLK Sentiment Intensity Analyzer:** 

The purpose of this section is to shift from creating a manual sentiment library of words to an analyzer with a corpus alreayd established. 

In [5]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [6]:
sentences =DailyDf['comments']

In [7]:
from nltk import tokenize

In [16]:
sid = SentimentIntensityAnalyzer()
>>> for sentence in sentences:
...     print(sentence)
...     ss = sid.polarity_scores(sentence)
...     for k in sorted(ss):
...         print('{0}: {1}, '.format(k, ss[k]), end='')
...     print()

Hello, how are you?
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0, 
Today is a good day!
compound: 0.4926, neg: 0.0, neu: 0.484, pos: 0.516, 
It's my birthday so it's a really special day!
compound: 0.5497, neg: 0.0, neu: 0.664, pos: 0.336, 
Today is neither a good day or a bad day!
compound: -0.735, neg: 0.508, neu: 0.492, pos: 0.0, 
I'm having a bad day.
compound: -0.5423, neg: 0.538, neu: 0.462, pos: 0.0, 
There' s nothing special happening today.
compound: -0.3089, neg: 0.361, neu: 0.639, pos: 0.0, 
Today is a SUPER good day!
compound: 0.8327, neg: 0.0, neu: 0.277, pos: 0.723, 


**Examples of how to complete sentiment analysis on Twitter comments:**

The purpose of this section is to examine the sentiment as they relate to some trending comments from twitter. 

In [18]:
import twitter

## Removed Twitter login info while uploading to GitHub


In [19]:
tweets=api.GetSearch(term='Breonna Taylor', since=2016-11-21, count=10)
tweets

[Status(ID=1309981909699756039, ScreenName=robferdman, Created=Sat Sep 26 22:23:20 +0000 2020, Text='Breaking: New Body-Cam Footage Raises Questions About Breonna Taylor Death\xa0Investigation https://t.co/PAZ4C9tPuK'),
 Status(ID=1310259004476592130, ScreenName=ava, Created=Sun Sep 27 16:44:24 +0000 2020, Text='BREAKING: “A Kentucky State Police ballistics report does not support Attorney General Daniel Cameron’s assertion t… https://t.co/8lE8VjKo7b'),
 Status(ID=1309932036795314176, ScreenName=robferdman, Created=Sat Sep 26 19:05:09 +0000 2020, Text='Breaking: The Only Witness Who Heard Police Announce Themselves at Breonna Taylor’s Door Changed His Story https://t.co/aigLNU4fkZ'),
 Status(ID=1310293057120669699, ScreenName=Pnut_Malika, Created=Sun Sep 27 18:59:43 +0000 2020, Text="RT @JoyAnnReid: The Breonna Taylor shooting and Kentucky AG Daniel Cameron’s behavior still don’t add up. New: Ballistics don't support Cam…"),
 Status(ID=1310293050141347841, ScreenName=MarlyMawl, Created

In [20]:
dfBreonnaTaylor_Tweets=pd.DataFrame (data=[tweet.text for tweet in tweets], columns = ['Text'])

In [21]:
BTSentences= dfBreonnaTaylor_Tweets['Text']

In [22]:
sid = SentimentIntensityAnalyzer()
>>> for sentence in BTSentences:
...     print(sentence)
...     ss = sid.polarity_scores(sentence)
...     for k in sorted(ss):
...         print('{0}: {1}, '.format(k, ss[k]), end='')
...     print()

Breaking: New Body-Cam Footage Raises Questions About Breonna Taylor Death Investigation https://t.co/PAZ4C9tPuK
compound: -0.5994, neg: 0.262, neu: 0.738, pos: 0.0, 
BREAKING: “A Kentucky State Police ballistics report does not support Attorney General Daniel Cameron’s assertion t… https://t.co/8lE8VjKo7b
compound: -0.3089, neg: 0.124, neu: 0.876, pos: 0.0, 
Breaking: The Only Witness Who Heard Police Announce Themselves at Breonna Taylor’s Door Changed His Story https://t.co/aigLNU4fkZ
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0, 
RT @JoyAnnReid: The Breonna Taylor shooting and Kentucky AG Daniel Cameron’s behavior still don’t add up. New: Ballistics don't support Cam…
compound: -0.3089, neg: 0.101, neu: 0.899, pos: 0.0, 
RT @tariqnasheed: Over a dozen witnesses confirmed that the race soldiers did NOT announce themselves when they lynched Breonna Taylor. The…
compound: 0.0, neg: 0.0, neu: 1.0, pos: 0.0, 
RT @JoyAnnReid: The Breonna Taylor shooting and Kentucky AG Daniel Cameron’s be

**Discussion:** 

As very much expected, there is a lot of social unrest toward Breonna Taylors death and sentiment here shows that. This exercise also was done without preprocessing and would be interesting to compare and contrast sentiment for these selected items to understand sentiment as an exercise in the future. 